name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: '20'

jobs:
  test:
    name: Test and Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run type check
        run: npm run typecheck

      - name: Build TypeScript
        run: npm run build:ts

      - name: Test npm package
        run: |
          # Test that the built package can be installed
          npm pack
          npm install -g ./sethdouglasford-claude-flow-*.tgz
          claude-flow --version

  build-sea:
    name: Build SEA Binary
    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build SEA binary
        run: npm run build

      - name: Test SEA binary
        run: |
          ./bin/claude-flow --version
          ./bin/claude-flow help

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: claude-flow-linux
          path: bin/claude-flow
          retention-days: 7
